apiVersion: apps/v1
kind: Deployment
metadata:
  name: linklite-link-enrichment-worker
  namespace: linklite-preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linklite
      app.kubernetes.io/component: link-enrichment-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linklite
        app.kubernetes.io/component: link-enrichment-worker
    spec:
      containers:
        - name: link-enrichment-worker
          image: ghcr.io/raresmusea/linklite-worker:testing-current
          command: ["node", "dist/worker/link_enrichment/link_enrichment_worker.js"]
          resources:
            requests:
              cpu: "50m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "384Mi"
          envFrom:
            - configMapRef:
                name: linklite-config
            - secretRef:
                name: linklite-secrets
