apiVersion: v1
kind: Secret
metadata:
  name: linklite-secrets
  namespace: linklite-preprod
type: Opaque
stringData:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""
  POSTGRES_DB_PORT: ""
  PRISMA_CLIENT_ENGINE_TYPE: ""
  IP_HASH_SALT: ""
  REDIS_URL: ""
  BETTER_AUTH_SECRET: ""
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_PORT: ""
  EMAIL_FROM: ""
  AWS_REGION: ""